### PR TITLE
Should clear context even in case of exceptions

### LINKED ISSUE #10: ContextProvider is not always cleared
If serializeAsField call throws an exception in JsonFieldsFilterProvider then popContext is never called. In the case of ThreadLocalContextProvider (the default), this means all future executions by the same thread will give wrong results.

### PR DESCRIPTION
**Pull request by duergner**
This will prevent from a broken context especially when working with a ThreadLocalContextProvider.

Will fix #10

### CODE REVIEW

**Comment by duergner** [comment]
@akf0 you might as well have a look as it should fix the issue you reported.

File: jackson/src/main/java/org/zalando/guild/api/json/fields/jackson/JsonFieldsFilterProvider.java [hunk 1]
```diff
@@ -96,8 +96,12 @@ public void serializeAsField(final Object pojo, final JsonGenerator jgen, final
             final FieldPredicate fieldPredicate = predicateSupplier.get();
             if (fieldPredicate.apply(qualifiedPath(name))) {
                 contextProvider.pushContext(name);
-                delegate.serializeAsField(pojo, jgen, prov, writer);
-                contextProvider.popContext();
+                try {
+                    delegate.serializeAsField(pojo, jgen, prov, writer);
+                }
+                finally {
```
Comment (fmueller) [inline jackson/src/main/java/org/zalando/guild/api/json/fields/jackson/JsonFieldsFilterProvider.java]: Can you please put this on line of closing bracket before - to have it consistent with codestyle in this codebase.

**Comment by duergner** [comment]
@fmueller addressed the comment

**Comment by fmueller** [comment]
👍
